version: "3.9"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    entrypoint: /code/backend_entrypoint.sh
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    entrypoint: /code/celery_entrypoint.sh
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data: