version: "3.9"

services:
  web:
    build: .
    command: gunicorn test_uchet_kz.wsgi:application --bind 0.0.0.0:8000
    entrypoint: /code/backend_entrypoint.sh
    volumes:
      - static_volume:/code/staticfiles
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    entrypoint: /code/celery_entrypoint.sh
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - web
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: